
project_id = "ecxrbonlltlnqhfhiggo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"

[functions]
enabled = true
