// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecxrbonlltlnqhfhiggo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjeHJib25sbHRsbnFoZmhpZ2dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNTQ5MTUsImV4cCI6MjA1MzgzMDkxNX0.YP7VTlAyI-SV2cFANDJYrgZJzFlfZuBO7_pgwjZGo_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);